
    <div class="container">
        <center><h2>Administrador</h2></center>
    <form>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="id" class="sr-only">Id cliente</label>
                    <input type="number" class="form-control" name="id cliente" placeholder="Id cliente">
                </div>
                <div class="form-group col-md-8">
                    <label for="nombre" class="sr-only">Nombre</label>
                    <input type="text" class="form-control" name="nombre" placeholder="Nombre">
                </div>        
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label for="id tipo documento" class="sr-only">Id tipo documento</label>
                    <select class="form-control" id="exampleFormControlSelect1">
                        <option>Tipo de documento</option>
                        <option value="1">Targeta de identidad</option>
                        <option value="2">Cédula</option>
                        <option value="3">Cédula extranjera</option>
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label for="documento" class="sr-only">Documento</label>
                    <input type="text" class="form-control" name="documento" placeholder="Documento">
                </div>
                <div class="form-group col-md-3">
                    <label for="id rol" class="sr-only">Id rol</label>
                    <input type="number" class="form-control" name="id rol" placeholder="Id rol">
                </div>
                <div class="form-group col-md-3">
                    <label for="telefono" class="sr-only">Telefono</label>
                    <input type="number" class="form-control" name="telefono" placeholder="Telefono">
                </div>
            </div>
                <hr>
                <hr>
            <div class="form-row">
                
                <div class="form-group col-md-6 offset-md-3">
                    <label for="correo" class="sr-only">Correo</label>
                    <input type="email" class="form-control" name="correo" placeholder="Correo">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 offset-md-3">
                    <label for="contraseña" class="sr-only">Contraseña</label>
                    <input type="password" class="form-control" name="contraseña" placeholder="Contraseña">
                </div>
            </div>
                <hr>
                <hr>
            
            
            <button type="submit" class="btn btn-primary  btn-lg btn-block">Guardar</button>
        </form>
        
    </div>
   
    
