

    <div class="container">
        <form action="bitacora2.php">
               
            <div class="form-group row">
                
                <div class="col-6">
                    <input type="number" class="form-control" name="id_usuario" placeholder="Id del usuario">
                </div>
                <div class="col-6">
                    <input type="number" class="form-control" name="id_ubicacion" placeholder="Id de la ubicación">
                </div>
            </div>
                <hr>
            <div class="form-group row">
                
                <div class="col-6">
                    <input type="number" class="form-control" name="id_estado" placeholder="Id del estado">
                </div>
                <div class="col-6">
                    <input type="date" class="form-control" name="fecha" placeholder="Fecha actual">
                </div>
            </div>
            <hr>
           
            <div class="container">
                <div class="form-group row">
                    
                    <button type="submit" class="btn btn-primary btn-md col-8 offset-2">Registrar</button>

                </div>
                
                
            </div>
            
                
        </form>
   
        

    </div>
  



