
<div class="container">
        <center><h2>CLIENTE</h2></center>
    <form action="cliente2.php" method="$_GET">
            <div class="form-row">
               
                <div class="form-group col-md-12">
                    <input type="text" class="form-control" name="nombre" placeholder="Nombre">
                </div>        
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-4">                   
                    <input type="number" class="form-control" name="id_tipo_documento" placeholder="Tipo de documento">
                </div>
                <div class="form-group col-md-8">                   
                    <input type="number" class="form-control" name="documento" placeholder="Documento">
                </div>
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-8 offset-md-2">
                    <input type="email" class="form-control" name="correo" placeholder="Correo electronico">     

                </div>              
            </div>
        
            <div class="form-row">
                <div class="form-group col-md-8 offset-md-2">
                <input type="password" class="form-control" name="contraseña" placeholder="Contraseña">
                <small id="helpId" class="text-muted">* Debe tener mas de 8 carácteres</small>
                </div>
            </div>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <div class="form-group">                       
                        <input type="number" class="form-control" name="id_rol" placeholder="Rol del usuario">
                    </div>
                </div>
               
                <div class="form-group col-md-6">
                   <input type="number" class="form-control" name="telefono" placeholder="Teléfono">
                </div>
            </div>
                <hr>
            
            <button type="submit" class="btn btn-primary  btn-lg btn-block">Registrar</button>
        </form>
        
    </div>
    
