
    <div class="container">
        <center><h2>CURSOS</h2></center>
        <form action="cursos2.php" method="$_GET">
                <div class="form-row">
                   
                    <div class="form-group col-md-4">
                        
                        <input type="number" class="form-control" name="numero_curso" placeholder="Ficha curso">
                    </div>
                    <div class="form-group col-md-8">
                        
                        <input type="text" class="form-control" name="curso" placeholder="Curso">
                    </div>        
                </div>
                    <hr>
                <div class="form-row">
                   
                   <div class="form-group col-md-6">
                       
                       <input type="number" class="form-control" name="id_nivel_curso" placeholder="Nivel del curso">
                   </div>
                   <div class="form-group col-md-6">
                       
                       <input type="number" class="form-control" name="id_jornada_curso" placeholder="Jornada del curso">
                   </div>        
               </div>
                    
                    <hr>
                    
                
                <button type="submit" class="btn btn-primary  btn-lg btn-block">Guardar</button>
            </form>
            
        </div>
