<form action="log_cliente2.php" method="$_GET">
    <div class="form-group row">
        <div class="form_group col-6">
            <input type="text" name="id_cliente" class="form-control" placeholder="Id del cliente">            
        </div>
        <div class="form_group col-6">
            <input type="date" name="fecha" class="form-control" placeholder="Fecha">            
        </div>
    </div>
    <hr>
    <div>
        <textarea class="form-control" placeholder="Novedad" name="novedad"></textarea>
    </div>
    <hr>
    <input type="submit" class="btn btn-primary btn-md col-8 offset-2" value="Guardar">
</form>