
    
    <div class="container">
        <center><h2>Administrador</h2></center>
        <form action="">
            <div class="form-group">
                <label for="exampleInputEmail1">Usuario</label>
                <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Usuario de administrador">
            
            </div>
            <hr>
            <div class="form-group">
                <label for="contraseña">Contraseña</label>
                <input type="password" class="form-control" id="contraseña" name="contraseña" placeholder="Contraseña">
            </div>
            <hr><br>           
           
            <input type="button" class="btn btn-primary btn-md col-8 offset-2" value="INGRESAR" onclick="location.href='../controlador/usuario.php' ">
        </form>
       
        

    </div>

    