<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/estilo.css">
</head>
<body>
    <header class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand">Control Covid19</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- ^^ Titula de la página ^^^^ -->




        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="../controlador/login.php">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="../controlador/loginsup.php">Login SuperUs</a>               
            </li>                   
            <li class="nav-item">
                <a class="nav-link" href="../controlador/bitacora.php">Bitacora</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="../controlador/usuario.php">Usuarios</a>               
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="../controlador/ubicacion.php">Ubicaciones</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="../controlador/cursos.php">Cursos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="../controlador/cliente.php">Cliente</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Consultas
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="../controlador/TabUsuario.php">Usuario</a>
                <a class="dropdown-item" href="../controlador/TabUbicacion.php">Ubicacion</a>
                <a class="dropdown-item" href="../controlador/TabFicha.php">Ficha</a>
                <a class="dropdown-item" href="../controlador/InfoUsuario.php">Informe de usuario</a>
                <a class="dropdown-item" href="../controlador/InfoAmbiente.php">Informe de Ambiente</a>
                <a class="dropdown-item" href="../controlador/InfoCurso.php">Informe de Ficha</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Datos sec...
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="../controlador/documento.php">Tipos Documento</a>
                <a class="dropdown-item" href="../controlador/roles.php">Roles</a>
                <a class="dropdown-item" href="../controlador/jornadas.php">Jornadas</a>
                <a class="dropdown-item" href="../controlador/estados.php">Estados</a>
                <a class="dropdown-item" href="../controlador/sedes.php">Sedes</a>
                <a class="dropdown-item" href="../controlador/nivel.php">Niveles</a>
                <a class="dropdown-item" href="../controlador/log_cliente.php">Movimientos del cliente</a>
              
                </div>
            </li>
            
        
            </ul>
        </div>
        
        </nav>
       
    </header>
    
    
    <div class="container">

      <?php include_once($seccion); ?>

    </div>



    


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>
