<div class="container">
    <center><h2>Fichas</h2></center>
    <div class="table-responsive-sm">
        <table class="table table-bordered table-hover">
            <tr>
                <th>Id</th>
                <th>Ficha</th>
                <th>Curso</th>
                <th>Nivel</th>
                <th>Jornada</th>
                
            </tr>
            <tr>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
               
            </tr>

        </table>
    </div>
    
</div>