<div class="container">
    <center><h2>Usuarios</h2></center>
    <div class="table-responsive-sm">
        <table class="table table-bordered table-hover">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Tipo documento</th>
                <th>Documento</th>
                <th>Rol</th>
                <th>Curso</th>
            </tr>
            <tr>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
            </tr>

        </table>
    </div>
    
</div>