<div class="container">
    <center><h2>Ubicaciones</h2></center>
    <div class="table-responsive-sm">
        <table class="table table-bordered table-hover">
            <tr>
                <th>Id</th>
                <th>Ubicación</th>
                <th>Detalles</th>
                <th>Sede</th>
               
            </tr>
            <tr>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
                <td>Info</td>
               
            </tr>

        </table>
    </div>
    
</div>