
    <div class="container">
        <center><h2>UBICACIONES</h2></center>
    <form action="ubicacion2.php" method="$_GET">
            <div class="form-row">
                
                <div class="form-group col-md">
                    <label for="ubicacion" class="sr-only">Ubicación</label>
                    <input type="text" class="form-control" name="ubicacion" placeholder="Ubicación">
                </div>        
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-8">
                    <label for="descripcion" class="sr-only">Descripción</label>
                    <input type="text" class="form-control" name="descripcion" placeholder="Descripción">
                </div>
                <div class="form-group col-md-4">
                    <label for="id sede" class="sr-only">Id sede</label>
                    <input type="number" class="form-control" name="id_sede" placeholder="Id sede">
                </div>
            </div>
                
                <hr>
            
            <button type="submit" class="btn btn-primary  btn-lg btn-block">Guardar</button>
        </form>
        
    </div>
   
