
   <div class="container">
        <center><h2>USUARIOS</h2></center>
    <form action="usuario2.php" method="$_GET">
            <div class="form-row">
               
                <div class="form-group col-md-12">
                    <input type="text" class="form-control" name="nombre" placeholder="Nombre">
                </div>        
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-4">                   
                    <input type="number" class="form-control" name="id_tipo_documento" placeholder="Tipo de documento">
                </div>
                <div class="form-group col-md-8">                   
                    <input type="text" class="form-control" name="documento" placeholder="Documento">
                </div>
            </div>
                <hr>
            <div class="form-row">
                <div class="form-group col-md-4">
                <input type="number" class="form-control" name="id_rol" placeholder="Rol del usuario">
                </div>
                <div class="form-group col-md-4">
                <input type="number" class="form-control" name="id_estado" placeholder="Estado del usuario">
                </div>
               
                <div class="form-group col-md-4">
                <input type="number" class="form-control" name="id_curso" placeholder="Curso del usuario">
                </div>
            </div>
                <hr>
            
            <button type="submit" class="btn btn-primary  btn-lg btn-block">Registrar</button>
        </form>
        
    </div>
 